DROP TABLE IF EXISTS PUBLIC.USER;
CREATE TABLE PUBLIC.USER
(
    id BIGINT PRIMARY KEY NOT NULL,
    username VARCHAR(30) NOT NULL,
    password VARCHAR(32) NOT NULL,
    firstName VARCHAR(30) NOT NULL,
    lastName VARCHAR (30),
    patronymic VARCHAR (30),
);
COMMIT;
